source 'https://rubygems.org'

gem 'sinatra', :require => 'sinatra/base'
gem 'sinatra-contrib'
gem 'rack-contrib'
gem 'logger'
gem 'mongoid', '~> 3.0.0'
gem 'thin'
gem 'shotgun'
gem 'dalli'
gem 'rack-cache'
gem 'guard'
gem 'guard-sass'